import type { CourseInfoForm } from "@thicket/platform/CourseBuilder/CourseInfoForm"
import { GALLERY_CATEGORIES } from "@thicket/platform/gallery/mocks/galleryData"
import type { GalleryEntry } from "@thicket/platform/gallery/registry/types"
import type { GalleryComponentMeta } from "@thicket/platform/gallery/types"

type CourseInfoFormProps = React.ComponentProps<typeof CourseInfoForm>

const courseInfoFormMeta: GalleryComponentMeta = {
  id: "course-builder/course-info-form",
  sourceId: "@thicket/platform/CourseBuilder/CourseInfoForm#CourseInfoForm",
  status: 'prod',
}

export const courseInfoFormGalleryEntry: GalleryEntry<CourseInfoFormProps> = {
  name: 'CourseInfoForm',
  importPath: '@thicket/platform/CourseBuilder/CourseInfoForm',
  category: 'Course Management',
  id: courseInfoFormMeta.id,
  meta: courseInfoFormMeta,
  layoutSize: 'full',
  variants: [
    {
      name: 'Empty Form',
      description: 'Initial state with no data filled',
      props: {
        title: '',
        description: '',
        categoryId: null,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {},
      },
      status: 'prod',
      category: 'state',
    },
    {
      name: 'Title Only',
      description: 'Form with just course title entered',
      props: {
        title: 'Introduction to Machine Learning',
        description: '',
        categoryId: null,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Partially Filled',
      description: 'Form with some data filled in',
      props: {
        title: 'Advanced React Development',
        description: 'Learn modern React patterns including hooks, context, and performance optimization',
        categoryId: null,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Complete Form',
      description: 'Form with all fields filled',
      props: {
        title: 'Full Stack JavaScript Bootcamp',
        description: 'Master modern web development with JavaScript, Node.js, React, and databases. Build real-world applications from scratch.',
        categoryId: 90001,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Long Description',
      description: 'Form with comprehensive multi-paragraph description',
      props: {
        title: 'Data Science Fundamentals',
        description: 'This comprehensive course covers the essential concepts and techniques in data science. You will learn statistical analysis, data visualization, machine learning algorithms, and how to apply these skills to real-world problems. By the end of this course, you will be proficient in using Python for data analysis, creating insightful visualizations, building predictive models, and communicating your findings effectively to stakeholders.',
        categoryId: 90002,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'With Validation Errors',
      description: 'Form showing validation error messages',
      props: {
        title: '',
        description: 'Short',
        categoryId: null,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {
          title: 'Course title is required',
          description: 'Description must be at least 20 words',
          status: 'prod',
          category: 'Please select a category',
        },
      },
      category: 'state',
    },
    {
      name: 'Single Error - Title',
      description: 'Form with only title error displayed',
      props: {
        title: '',
        description: 'Learn the fundamentals of web development including HTML, CSS, and JavaScript. Build responsive websites and understand modern development workflows.',
        categoryId: 90001,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {
          title: 'Course title is required',
        },
      },
      status: 'prod',
      category: 'state',
    },
    {
      name: 'Single Error - Description',
      description: 'Form with only description error displayed',
      props: {
        title: 'Web Development Basics',
        description: 'Too short',
        categoryId: 90001,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {
          description: 'Description must be at least 50 characters',
        },
      },
      status: 'prod',
      category: 'state',
    },
    {
      name: 'Single Error - Category',
      description: 'Form with only category error displayed',
      props: {
        title: 'Introduction to Python Programming',
        description: 'A comprehensive introduction to Python programming language covering syntax, data structures, functions, and object-oriented programming concepts.',
        categoryId: null,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {
          status: 'prod',
          category: 'Please select a category',
        },
      },
      category: 'state',
    },
    {
      name: 'Empty Categories List',
      description: 'Form when no categories are available in system',
      props: {
        title: 'Advanced Cloud Computing',
        description: 'Deep dive into cloud architecture, microservices, and containerization.',
        categoryId: null,
        categories: [],
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Many Categories',
      description: 'Form with extensive category list showing dropdown behavior',
      props: {
        title: 'Business Analytics',
        description: 'Learn to analyze business data and make data-driven decisions.',
        categoryId: 90003,
        categories: GALLERY_CATEGORIES,
        onTitleChange: (value) => console.log('Title:', value),
        onDescriptionChange: (value) => console.log('Description:', value),
        onCategoryChange: (value) => console.log('Category:', value),
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
  ],
}
