import type { ComponentProps } from 'react'
import type { GalleryComponentMeta } from '@thicket/platform/gallery/types'
import type { GalleryEntry } from "@thicket/platform/gallery/registry/types"
import type { Badge } from "@thicket/components/ui/badge"
import { propSchemas } from "@thicket/platform/gallery/registry/schema-helpers"

type BadgeProps = ComponentProps<typeof Badge>

export const badgeMeta: GalleryComponentMeta = {
  id: 'ui/badge',
  sourceId: '@thicket/components/ui/badge#Badge',
  status: 'prod',
}

export const badgeGalleryEntry: GalleryEntry<BadgeProps> = {
  name: 'Badge',
  importPath: badgeMeta.sourceId.split('#')[0],
  category: 'Base UI',
  id: badgeMeta.id,
  layoutSize: 'small',
  meta: badgeMeta,
  variants: [
    {
      name: 'Interactive',
      description: 'Customize badge text and variant live',
      props: { variant: 'brand', children: 'Badge', size: 'md' },
      status: 'prod',
      category: 'interactive',
      interactive: true,
      interactiveSchema: propSchemas.badgeSchema(),
    },
    {
      name: 'Default',
      description: 'Standard neutral badge',
      props: { children: 'Default' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Brand',
      description: 'Brand colored badge',
      props: { variant: 'brand', children: 'Brand' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Brand Filled',
      description: 'Solid brand badge',
      props: { variant: 'brand-filled', children: 'Featured' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Brand Outline',
      description: 'Outlined brand badge',
      props: { variant: 'brand-outline', children: 'New' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Filled',
      description: 'Gradient filled badge',
      props: { variant: 'filled', children: 'Premium' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Primary',
      description: 'Primary badge',
      props: { variant: 'brand', children: 'Primary' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Secondary',
      description: 'Secondary badge',
      props: { variant: 'secondary', children: 'Secondary' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Success',
      description: 'Success state badge',
      props: { variant: 'success', children: 'Success' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Info',
      description: 'Information badge',
      props: { variant: 'info', children: 'Info' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Warning',
      description: 'Warning badge',
      props: { variant: 'warning', children: 'Warning' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Neutral',
      description: 'Neutral badge',
      props: { variant: 'neutral', children: 'Neutral' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Extra Small',
      description: 'Extra small badge size',
      props: { variant: 'brand', size: 'xs', children: 'XS' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Small',
      description: 'Small badge size',
      props: { variant: 'brand', size: 'sm', children: 'Small' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Medium',
      description: 'Medium badge size (default)',
      props: { variant: 'brand', size: 'md', children: 'Medium' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Large',
      description: 'Large badge size',
      props: { variant: 'brand', size: 'lg', children: 'Large' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Student Count',
      description: 'Badge with Users icon for enrollment counts',
      props: { variant: 'secondary', size: 'sm', icon: 'Users', children: '24 students' },
      status: 'prod',
      category: 'icon-patterns',
    },
    {
      name: 'Announcement',
      description: 'Badge with Megaphone icon for announcements',
      props: { variant: 'brand-filled', size: 'xs', icon: 'Megaphone', children: 'New Update' },
      status: 'prod',
      category: 'icon-patterns',
    },
    {
      name: 'Course Indicator',
      description: 'Badge with BookOpen icon for courses',
      props: { variant: 'brand', size: 'xs', icon: 'BookOpen', children: 'Advanced Course' },
      status: 'prod',
      category: 'icon-patterns',
    },
    {
      name: 'Featured',
      description: 'Badge with Star icon for featured content',
      props: { variant: 'brand-filled', size: 'md', icon: 'Star', children: 'Popular' },
      status: 'prod',
      category: 'icon-patterns',
    },
    {
      name: 'Schedule',
      description: 'Badge with Calendar icon for dates',
      props: { variant: 'brand-outline', size: 'sm', icon: 'Calendar', children: 'Today at 3pm' },
      status: 'prod',
      category: 'icon-patterns',
    },
    {
      name: 'Brand with Icon',
      description: 'Brand variant with BookOpen icon',
      props: { variant: 'brand', icon: 'BookOpen', children: 'Course' },
      status: 'prod',
      category: 'icon-basics',
    },
    {
      name: 'Brand Filled with Icon',
      description: 'Brand filled variant with Megaphone icon',
      props: { variant: 'brand-filled', icon: 'Megaphone', children: 'Announcement' },
      status: 'prod',
      category: 'icon-basics',
    },
    {
      name: 'Brand Outline with Icon',
      description: 'Brand outline variant with Calendar icon',
      props: { variant: 'brand-outline', icon: 'Calendar', children: 'Upcoming' },
      status: 'prod',
      category: 'icon-basics',
    },
    {
      name: 'Secondary with Icon',
      description: 'Secondary variant with Users icon',
      props: { variant: 'secondary', icon: 'Users', children: 'Students' },
      status: 'prod',
      category: 'icon-basics',
    },
    {
      name: 'Success with Icon',
      description: 'Success variant with Check icon',
      props: { variant: 'success', icon: 'Check', children: 'Verified' },
      status: 'prod',
      category: 'icon-basics',
    },
    {
      name: 'Info with Icon',
      description: 'Info variant with Info icon',
      props: { variant: 'info', icon: 'Info', children: 'Information' },
      status: 'prod',
      category: 'icon-basics',
    },
    {
      name: 'Warning with Icon',
      description: 'Warning variant with AlertCircle icon',
      props: { variant: 'warning', icon: 'AlertCircle', children: 'Alert' },
      status: 'prod',
      category: 'icon-basics',
    },
    {
      name: 'Neutral with Icon',
      description: 'Neutral variant with Clock icon',
      props: { variant: 'neutral', icon: 'Clock', children: 'Duration' },
      status: 'prod',
      category: 'icon-basics',
    },
    {
      name: 'Icon XS Size',
      description: 'Extra small icon scaling',
      props: { variant: 'brand', size: 'xs', icon: 'Users', children: 'XS' },
      status: 'prod',
      category: 'icon-sizes',
    },
    {
      name: 'Icon SM Size',
      description: 'Small icon scaling',
      props: { variant: 'brand', size: 'sm', icon: 'Users', children: 'Small' },
      status: 'prod',
      category: 'icon-sizes',
    },
    {
      name: 'Icon MD Size',
      description: 'Medium icon scaling (default)',
      props: { variant: 'brand', size: 'md', icon: 'Users', children: 'Medium' },
      status: 'prod',
      category: 'icon-sizes',
    },
    {
      name: 'Icon LG Size',
      description: 'Large icon scaling',
      props: { variant: 'brand', size: 'lg', icon: 'Users', children: 'Large' },
      status: 'prod',
      category: 'icon-sizes',
    },
    {
      name: 'Primary with Icon',
      description: 'Primary variant with Award icon',
      props: { variant: 'brand', icon: 'Award', children: 'Achievement' },
      status: 'prod',
      category: 'icon-basics',
    },
    {
      name: 'Filled with Icon',
      description: 'Gradient filled variant with Sparkles icon',
      props: { variant: 'filled', icon: 'Sparkles', children: 'Premium' },
      status: 'prod',
      category: 'icon-basics',
    },
    // Real page usage variants (from variantUsage.generated.json)
    {
      name: 'Brand Filled Small',
      description: 'Small brand filled badge for emphasis',
      props: { variant: 'brand-filled', size: 'sm', children: 'Live' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Default Medium',
      description: 'Standard medium default badge',
      props: { variant: 'default', size: 'md', children: 'Tag' },
      status: 'prod',
      category: 'size',
    },
  ],
}
