import type { ButtonProps } from "../../components/ui/button"
import type { GalleryComponentMeta } from '../../platform/gallery/types'
import type { GalleryEntry } from "../../platform/gallery/registry/types"
import { propSchemas } from "../../platform/gallery/registry/schema-helpers"

export const buttonMeta: GalleryComponentMeta = {
  id: 'ui/button',
  sourceId: '../../components/ui/button#Button',
  status: 'prod',
}

export const buttonGalleryEntry: GalleryEntry<ButtonProps> = {
  name: 'Button',
  importPath: buttonMeta.sourceId.split('#')[0],
  category: 'Base UI',
  id: buttonMeta.id,
  layoutSize: 'small',
  meta: buttonMeta,
  variants: [
    {
      name: 'Interactive',
      description: 'Customize button properties and see changes live',
      props: { variant: 'brand', size: 'md', children: 'Click Me' },
      status: 'prod',
      category: 'interactive',
      interactive: true,
      interactiveSchema: propSchemas.buttonSchema(),
    },
    {
      name: 'Primary',
      description: 'Main call-to-action button',
      props: { variant: 'brand', children: 'Get Started' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Primary with Icon',
      description: 'Primary button with icon',
      props: { variant: 'brand', children: 'Continue', icon: 'ArrowRight' },
      status: 'archive',
      category: 'variant',
    },
    {
      name: 'Secondary',
      description: 'Secondary action button',
      props: { variant: 'secondary', children: 'Learn More' },
      status: 'archive',
      category: 'variant',
    },
    {
      name: 'Waitlist',
      description: 'Waitlist signup button',
      props: { variant: 'waitlist', children: 'Join Waitlist' },
      status: 'archive',
      category: 'variant',
    },
    {
      name: 'Waitlist Soft',
      description: 'Soft waitlist button style',
      props: { variant: 'waitlist-soft', children: 'Join Waitlist' },
      status: 'archive',
      category: 'variant',
    },
    {
      name: 'Enrolled',
      description: 'Enrolled state - automatically disabled with unique styling',
      props: { variant: 'enrolled', children: 'Enrolled' },
      status: 'prod',
      category: 'state',
    },
    {
      name: 'Outline',
      description: 'Outlined button style',
      props: { variant: 'outline', children: 'View Details' },
      status: 'archive',
      category: 'variant',
    },
    {
      name: 'Ghost',
      description: 'Minimal button with no background',
      props: { variant: 'ghost', children: 'Cancel' },
      status: 'archive',
      category: 'variant',
    },
    {
      name: 'CTA',
      description: 'Call-to-action button with shadow',
      props: { variant: 'cta', children: 'Start Learning', fullWidth: false },
      status: 'archive',
      category: 'variant',
    },
    {
      name: 'Warning',
      description: 'Warning/destructive action button',
      props: { variant: 'warning', children: 'Delete Course' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Small Primary',
      description: 'Compact primary button',
      props: { variant: 'brand', size: 'sm', children: 'Small' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Medium Primary',
      description: 'Standard size primary button',
      props: { variant: 'brand', size: 'md', children: 'Medium' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Large Primary',
      description: 'Large prominent button',
      props: { variant: 'brand', size: 'lg', children: 'Large' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Loading Primary',
      description: 'Button with loading spinner',
      props: { variant: 'brand', isLoading: true, children: 'Processing' },
      status: 'archive',
      category: 'state',
    },
    {
      name: 'Disabled Primary',
      description: 'Disabled button state (50% opacity)',
      props: { variant: 'brand', disabled: true, children: 'Disabled' },
      status: 'prod',
      category: 'state',
    },
    {
      name: 'Full Width',
      description: 'Button spans full container width',
      props: { variant: 'brand', fullWidth: true, children: 'Full Width Button' },
      status: 'archive',
      category: 'size',
    },
    // Real page usage variants (from variantUsage.generated.json)
    {
      name: 'Small Secondary',
      description: 'Compact secondary action button',
      props: { variant: 'secondary', size: 'sm', children: 'Back' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Medium Outline',
      description: 'Standard outlined button for secondary actions',
      props: { variant: 'outline', size: 'md', children: 'Cancel' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Small Outline',
      description: 'Compact outlined button',
      props: { variant: 'outline', size: 'sm', children: 'Edit' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Small Ghost',
      description: 'Compact minimal button',
      props: { variant: 'ghost', size: 'sm', children: 'Skip' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Medium Ghost',
      description: 'Standard minimal button',
      props: { variant: 'ghost', size: 'md', children: 'Back' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Medium CTA',
      description: 'Call-to-action with standard size',
      props: { variant: 'cta', size: 'md', children: 'Get Started' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Rounded Large',
      description: 'Button with large border radius',
      props: { variant: 'brand', rounded: 'lg', children: 'Sign In' },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Small Rounded',
      description: 'Compact button with large border radius',
      props: { variant: 'brand', size: 'sm', rounded: 'lg', children: 'Back' },
      status: 'prod',
      category: 'size',
    },
    {
      name: 'Outline Rounded',
      description: 'Outlined button with large border radius',
      props: { variant: 'outline', rounded: 'lg', children: 'Learn More' },
      status: 'prod',
      category: 'variant',
    },
  ],
}
