import type { UnifiedLessonCardProps } from '@thicket/platform/UnifiedLessonCard'

import type { GalleryComponentMeta } from '@thicket/platform/gallery/types'
import type { GalleryEntry } from '../../registry/types'

export const unifiedLessonCardMeta: GalleryComponentMeta = {
  id: 'lessons/unified-lesson-card',
  sourceId: '@thicket/platform/UnifiedLessonCard#UnifiedLessonCard',
  status: 'prod',
}

export const unifiedLessonCardGalleryEntry: GalleryEntry<UnifiedLessonCardProps> = {
  id: unifiedLessonCardMeta.id,
  name: 'UnifiedLessonCard',
  importPath: unifiedLessonCardMeta.sourceId.split('#')[0],
  category: 'Unified Lesson Card',
  layoutSize: 'medium',
  meta: unifiedLessonCardMeta,
  variants: [
    {
      name: 'Student - Live Session (Dashboard)',
      description: 'Student view of live lesson in dashboard mode',
      props: {
        lesson: {
          id: 1,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90001,
          lessonTitle: 'Getting Started with HTML',
          lessonDescription: 'Learn the basics of HTML structure and semantic elements',
          lessonPosition: 1,
          scheduledAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
          wherebyRoomUrl: 'https://example.whereby.com/lesson-90001',
          topics: ['HTML5 Semantic Elements', 'Document Structure', 'Accessibility Basics'],
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'dashboard' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'student-live',
    },
    {
      name: 'Student - Live Session (Schedule)',
      description: 'Student view of live lesson in schedule mode',
      props: {
        lesson: {
          id: 2,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90001,
          lessonTitle: 'Getting Started with HTML',
          lessonDescription: 'Learn the basics of HTML structure and semantic elements',
          lessonPosition: 1,
          scheduledAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
          wherebyRoomUrl: 'https://example.whereby.com/lesson-90001',
          topics: ['HTML5 Semantic Elements', 'Document Structure', 'Accessibility Basics'],
          learningObjectives: ['Understand HTML5 semantic tags', 'Create accessible web pages', 'Build proper document structure'],
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
          classmatesCount: 24,
        },
        mode: 'schedule' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'student-live',
    },
    {
      name: 'Student - Live Session (Course Details)',
      description: 'Student view of live lesson in course details mode',
      props: {
        lesson: {
          id: 3,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90001,
          lessonTitle: 'Getting Started with HTML',
          lessonDescription: 'Learn the basics of HTML structure and semantic elements',
          lessonPosition: 1,
          scheduledAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
          wherebyRoomUrl: 'https://example.whereby.com/lesson-90001',
          topics: ['HTML5 Semantic Elements', 'Document Structure', 'Accessibility Basics'],
          learningObjectives: ['Understand HTML5 semantic tags', 'Create accessible web pages', 'Build proper document structure'],
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
          courseTimezone: 'America/Los_Angeles',
        },
        mode: 'course-details' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'student-live',
    },
    {
      name: 'Student - Live Session (Live Banner)',
      description: 'Student view of live lesson in live banner mode',
      props: {
        lesson: {
          id: 4,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90001,
          lessonTitle: 'Getting Started with HTML',
          lessonDescription: 'Learn the basics of HTML structure and semantic elements',
          lessonPosition: 1,
          scheduledAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
          wherebyRoomUrl: 'https://example.whereby.com/lesson-90001',
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'live-banner' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'student-live',
    },
    {
      name: 'Student - Upcoming Next Lesson',
      description: 'Student view of next upcoming lesson',
      props: {
        lesson: {
          id: 5,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90002,
          lessonTitle: 'CSS Styling Basics',
          lessonDescription: 'Introduction to CSS selectors, properties, and layouts',
          lessonPosition: 2,
          scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
          topics: ['CSS Selectors', 'Box Model', 'Flexbox Layouts'],
          learningObjectives: ['Master CSS selectors', 'Understand the box model', 'Create responsive layouts'],
          isCompleted: false,
          isLocked: false,
          isNext: true,
          userTimezone: 'America/New_York',
        },
        mode: 'course-details' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'student-upcoming',
    },
    {
      name: 'Student - Upcoming Lesson',
      description: 'Student view of future upcoming lesson',
      props: {
        lesson: {
          id: 6,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90003,
          lessonTitle: 'JavaScript Fundamentals',
          lessonDescription: 'Learn the core concepts of JavaScript programming',
          lessonPosition: 3,
          scheduledAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
          topics: ['Variables and Data Types', 'Functions', 'Control Flow'],
          learningObjectives: ['Understand JavaScript syntax', 'Write functions', 'Use conditional statements'],
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'schedule' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'student-upcoming',
    },
    {
      name: 'Student - Locked Lesson',
      description: 'Student view of locked lesson',
      props: {
        lesson: {
          id: 7,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90004,
          lessonTitle: 'Advanced JavaScript Patterns',
          lessonDescription: 'Explore advanced concepts like closures and async/await',
          lessonPosition: 4,
          scheduledAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
          topics: ['Closures', 'Promises', 'Async/Await'],
          learningObjectives: ['Master closures', 'Handle asynchronous code', 'Write clean async functions'],
          isCompleted: false,
          isLocked: true,
          userTimezone: 'America/New_York',
        },
        mode: 'course-details' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'student-locked',
    },
    {
      name: 'Student - Completed with Recording',
      description: 'Student view of completed lesson with recording available',
      props: {
        lesson: {
          id: 8,
          courseId: 90002,
          courseTitle: 'Advanced React Patterns',
          courseCoverUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
          lessonId: 90005,
          lessonTitle: 'React Hooks Deep Dive',
          lessonDescription: 'Master useState, useEffect, and custom hooks',
          lessonPosition: 1,
          scheduledAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
          startedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
          recordingUrl: 'https://example.whereby.com/recording/lesson-90005',
          topics: ['useState Hook', 'useEffect Hook', 'Custom Hooks'],
          learningObjectives: ['Master React hooks', 'Create custom hooks', 'Optimize component performance'],
          isCompleted: true,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'course-details' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'student-completed',
    },
    {
      name: 'Student - Past Lesson with Recording',
      description: 'Student view of past lesson with recording',
      props: {
        lesson: {
          id: 9,
          courseId: 90002,
          courseTitle: 'Advanced React Patterns',
          courseCoverUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
          lessonId: 90006,
          lessonTitle: 'Context API and State Management',
          lessonDescription: 'Learn global state management with Context API',
          lessonPosition: 2,
          scheduledAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
          recordingUrl: 'https://example.whereby.com/recording/lesson-90006',
          topics: ['Context API', 'useContext Hook', 'State Management'],
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'dashboard' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'student-past',
    },
    {
      name: 'Teacher - Live Session (Dashboard)',
      description: 'Teacher view of live lesson in dashboard mode',
      props: {
        lesson: {
          id: 10,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90001,
          lessonTitle: 'Getting Started with HTML',
          lessonDescription: 'Learn the basics of HTML structure and semantic elements',
          lessonPosition: 1,
          scheduledAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
          hostWherebyUrl: 'https://example.whereby.com/host/lesson-90001',
          enrolledStudentsCount: 24,
          topics: ['HTML5 Semantic Elements', 'Document Structure', 'Accessibility Basics'],
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'dashboard' as const,
        role: 'teacher' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'teacher-live',
    },
    {
      name: 'Teacher - Live Session (Live Banner)',
      description: 'Teacher view of live lesson in live banner mode',
      props: {
        lesson: {
          id: 11,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90001,
          lessonTitle: 'Getting Started with HTML',
          lessonDescription: 'Learn the basics of HTML structure and semantic elements',
          lessonPosition: 1,
          scheduledAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
          hostWherebyUrl: 'https://example.whereby.com/host/lesson-90001',
          enrolledStudentsCount: 24,
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'live-banner' as const,
        role: 'teacher' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'teacher-live',
    },
    {
      name: 'Teacher - Upcoming Next Lesson',
      description: 'Teacher view of next upcoming lesson',
      props: {
        lesson: {
          id: 12,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90002,
          lessonTitle: 'CSS Styling Basics',
          lessonDescription: 'Introduction to CSS selectors, properties, and layouts',
          lessonPosition: 2,
          scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
          enrolledStudentsCount: 24,
          topics: ['CSS Selectors', 'Box Model', 'Flexbox Layouts'],
          learningObjectives: ['Master CSS selectors', 'Understand the box model', 'Create responsive layouts'],
          isCompleted: false,
          isLocked: false,
          isNext: true,
          userTimezone: 'America/New_York',
        },
        mode: 'course-details' as const,
        role: 'teacher' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'teacher-upcoming',
    },
    {
      name: 'Teacher - Upcoming Lesson',
      description: 'Teacher view of future upcoming lesson',
      props: {
        lesson: {
          id: 13,
          courseId: 90002,
          courseTitle: 'Advanced React Patterns',
          courseCoverUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
          lessonId: 90007,
          lessonTitle: 'Performance Optimization',
          lessonDescription: 'Learn React performance optimization techniques',
          lessonPosition: 3,
          scheduledAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
          enrolledStudentsCount: 18,
          topics: ['React.memo', 'useMemo', 'useCallback', 'Code Splitting'],
          learningObjectives: ['Optimize React components', 'Reduce unnecessary re-renders', 'Implement lazy loading'],
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'schedule' as const,
        role: 'teacher' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'teacher-upcoming',
    },
    {
      name: 'Teacher - Past Lesson with Recording',
      description: 'Teacher view of past lesson with recording available',
      props: {
        lesson: {
          id: 14,
          courseId: 90002,
          courseTitle: 'Advanced React Patterns',
          courseCoverUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
          lessonId: 90005,
          lessonTitle: 'React Hooks Deep Dive',
          lessonDescription: 'Master useState, useEffect, and custom hooks',
          lessonPosition: 1,
          scheduledAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
          recordingUrl: 'https://example.whereby.com/recording/lesson-90005',
          enrolledStudentsCount: 18,
          topics: ['useState Hook', 'useEffect Hook', 'Custom Hooks'],
          isCompleted: true,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'course-details' as const,
        role: 'teacher' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'teacher-past',
    },
    {
      name: 'Teacher - Live Session (No Room URL)',
      description: 'Teacher view of live lesson without room URL',
      props: {
        lesson: {
          id: 15,
          courseId: 90003,
          courseTitle: 'UI/UX Design Fundamentals',
          courseCoverUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
          lessonId: 90008,
          lessonTitle: 'Design Principles',
          lessonDescription: 'Learn fundamental design principles',
          lessonPosition: 1,
          scheduledAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
          enrolledStudentsCount: 15,
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
        },
        mode: 'dashboard' as const,
        role: 'teacher' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'teacher-error',
    },
    {
      name: 'Timezone Conversion Example',
      description: 'Lesson showing timezone conversion badge',
      props: {
        lesson: {
          id: 16,
          courseId: 90001,
          courseTitle: 'Introduction to Web Development',
          courseCoverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
          lessonId: 90009,
          lessonTitle: 'Responsive Web Design',
          lessonDescription: 'Create websites that work on all devices',
          lessonPosition: 5,
          scheduledAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
          topics: ['Media Queries', 'Viewport Units', 'Responsive Images'],
          learningObjectives: ['Build responsive layouts', 'Use CSS Grid', 'Implement mobile-first design'],
          isCompleted: false,
          isLocked: false,
          userTimezone: 'America/New_York',
          courseTimezone: 'Europe/London',
        },
        mode: 'course-details' as const,
        role: 'student' as const,
        showActions: true,
      },
      status: 'prod',
      category: 'timezone',
    },
  ],
}
