import type { ScheduleForm } from "@/platform/components/CourseBuilder/ScheduleForm"
import type { GalleryEntry } from "../registry/types"
import type { GalleryComponentMeta } from "../registry/types"

type ScheduleFormProps = React.ComponentProps<typeof ScheduleForm>

const scheduleFormMeta: GalleryComponentMeta = {
  id: "course-builder/schedule-form",
  sourceId: "@/platform/components/CourseBuilder/ScheduleForm#ScheduleForm",
  status: 'prod',
}

export const scheduleFormGalleryEntry: GalleryEntry<ScheduleFormProps> = {
  name: 'ScheduleForm',
  importPath: '@/platform/components/CourseBuilder/ScheduleForm',
  category: 'Course Management',
  id: scheduleFormMeta.id,
  meta: scheduleFormMeta,
  layoutSize: 'full',
  variants: [
    {
      name: 'Empty State',
      description: 'Form with no date or time selected',
      props: {
        startDate: '',
        startTime: '',
        lessonLength: 1,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/New_York',
        errors: {},
      },
      status: 'prod',
      category: 'state',
    },
    {
      name: 'Date Only',
      description: 'Form with date selected but no time',
      props: {
        startDate: '2025-02-15',
        startTime: '',
        lessonLength: 1,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/New_York',
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Complete - 1 Hour EST',
      description: 'Form with date and time for 1-hour course in EST',
      props: {
        startDate: '2025-02-15',
        startTime: '14:00',
        lessonLength: 1,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/New_York',
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Complete - 1.5 Hours PST',
      description: 'Form with date and time for 1.5-hour course in PST',
      props: {
        startDate: '2025-03-01',
        startTime: '18:30',
        lessonLength: 1.5,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/Los_Angeles',
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Complete - 2 Hours CST',
      description: 'Form with date and time for 2-hour course in CST',
      props: {
        startDate: '2025-02-20',
        startTime: '19:00',
        lessonLength: 2,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/Chicago',
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Complete - 3 Hours UTC',
      description: 'Form with date and time for 3-hour workshop in UTC',
      props: {
        startDate: '2025-03-15',
        startTime: '10:00',
        lessonLength: 3,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'UTC',
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Morning Time',
      description: 'Early morning course start time',
      props: {
        startDate: '2025-02-10',
        startTime: '08:00',
        lessonLength: 1,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/New_York',
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'Evening Time',
      description: 'Evening course start time',
      props: {
        startDate: '2025-02-18',
        startTime: '20:00',
        lessonLength: 1,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/New_York',
        errors: {},
      },
      status: 'prod',
      category: 'variant',
    },
    {
      name: 'With Date Error',
      description: 'Form showing date validation error',
      props: {
        startDate: '',
        startTime: '14:00',
        lessonLength: 1,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/New_York',
        errors: {
          startDate: 'Start date is required',
        },
      },
      status: 'prod',
      category: 'state',
    },
    {
      name: 'With Time Error',
      description: 'Form showing time validation error',
      props: {
        startDate: '2025-02-15',
        startTime: '',
        lessonLength: 1,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/New_York',
        errors: {
          startTime: 'Start time is required',
        },
      },
      status: 'prod',
      category: 'state',
    },
    {
      name: 'With Both Errors',
      description: 'Form showing both date and time errors',
      props: {
        startDate: '',
        startTime: '',
        lessonLength: 1,
        onStartDateChange: (value) => console.log('Start date:', value),
        onStartTimeChange: (value) => console.log('Start time:', value),
        instructorTimezone: 'America/New_York',
        errors: {
          startDate: 'Start date is required',
          startTime: 'Start time is required',
        },
      },
      status: 'prod',
      category: 'state',
    },
  ],
}
